name: nf-core-mypipeline-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # TODO nf-core: Add required software dependencies here
  - fastqc=0.11.8
  #- trim-galore=0.4.4
  #- atropos=1.1.16
  #- multiqc=1.3
 # - python=3.6
