description:
    "This config file is designed to raw-qc pipeline."

author: "Mathieu Valade"

###TO MODIFY###

experience:
    RUN: "{{RUN}}"
    SEQUENCER: "{{ILLUMINA_SEQUENCER}}"
    PROJECT: "RAW-QC"
    PROJECT_SAMPLESHEET: "{{KDI_PROJECT}}"
    ILLUMINA_REF: "{{ILLUMINA_REF}}"
    ##CODE DEMAND
    DEMAND: "{{DEMAND}}"
    PROJECT_SAMPLESHEET: "{{KDI_PROJECT}}"

workflow_parameters:
    CHECK_TIME: "86400" #24h

kdi:
    ENV: "{{ENV}}" #dev,valid,prod
    UNDECLARED: "FALSE"  #TRUE or FALSE
    DATASET_ID: ""
    API_PATH: "/bioinfo/pipelines/kdi_api_scripts/{{ENV}}/"
    PROJECT_NAME: "{{KDI_PROJECT}}"
    TECHNICAL_PF: "{{ILLUMINA_SEQUENCER}}"
    ORGANISATION: "Plateforme NGS"
    BIOLOGICAL_CATEGORY: "{{BIOLOGICAL_CATEGORY}}"
    PROTOCOL: "{{PROTOCOL}}"
    DATASET_NAME: "{{RUN}}"
    RUN_CONF: ""
    PUBLISHED: "True"
    SPECIES: "{{KDI_SPECIES}}"
    SAMPLE_TYPE: "other"
    SAMPLE_ALIAS_TYPE: "BioinfoNGS sample identifier"
    REPLICATE_ALIAS_TYPE_NAME: "Platform id NGS"

run_information:
    RUN: "{{RUN}}"
    WORKFLOW: "none"
    DATA_TYPE: "{{DATATYPE}}"
    ANALYSIS: "raw"
    PIPELINE_NAME: "raw-qc"
    PIPELINE_TYPE: "{{SCOPE}}"
    EXPORT_PATH: "{{RAWQC_PATH}}/raw-qc_snakemake/KDI_conf/"
    EXPORT_TO_KDI_SAMPLE: "exportToKDI.conf"
    EXPORT_TO_KDI_RUNFILE: "exportToKDI-RunFiles.conf"

extension:
    SAMPLESHEET_CHECKER_INPUT_1: "SampleSheet.csv"
    SAMPLESHEET_CHECKER_INPUT_2: "{{ILLUMINA_FILE}}"
    SAMPLESHEET_CHECKER_OUTPUT: "SampleSheet.csv"
    BCL2FASTQ_INPUT: "SampleSheet.csv"
    BCL2FASTQ_OUTPUT: "Reports/html/index.html"
    CHECK_FASTQ_LENGTH_INPUT: "Reports/html/index.html"
    CHECK_FASTQ_LENGTH_OUTPUT: "check_fastq_length_ok.txt"
    TRANSFERT_FASTQ_DIR_INPUT: "check_fastq_length_ok.txt"
    TRANSFERT_FASTQ_DIR_OUTPUT: "transfert_fastq_dir_ok.txt"
    MANAGE_UNDETERMINED_FASTQ_INPUT: "transfert_fastq_dir_ok.txt"
    MANAGE_UNDETERMINED_FASTQ_OUTPUT: "manage_undetermined_fastq_ok.txt"
    SAMPLESHEET_TO_SAMPLEPLAN_INPUT_1: "manage_undetermined_fastq_ok.txt"
    SAMPLESHEET_TO_SAMPLEPLAN_INPUT_2: "SampleSheet.csv"
    SAMPLESHEET_TO_SAMPLEPLAN_OUTPUT: "_SAMPLEPLAN"
    SAMPLESHEET_TO_SAMPLEDESCRIPTION_INPUT: "_SAMPLEPLAN"
    SAMPLESHEET_TO_SAMPLEDESCRIPTION_OUTPUT: ".sampleDescription.txt"
    CONFIG_COPY_INPUT_1: "/config/rawqc_config.json"
    CONFIG_COPY_INPUT_2: ".sampleDescription.txt"
    CONFIG_COPY_OUTPUT_1: "rawqc_config.json"
    CONFIG_COPY_OUTPUT_2: "_config_copy_ok.txt"
    RIMS_METADATA_LAUNCHER_INPUT_1: "_config_copy_ok.txt"
    RIMS_METADATA_LAUNCHER_INPUT_2: "rawqc_config.json"
    RIMS_METADATA_LAUNCHER_OUTPUT: "-rims_metadata.tsv"
    RAW-QC_PIPELINE_INPUT_1: "SampleSheet.csv"
    RAW-QC_PIPELINE_INPUT_2: "rawqc_config.json"
    RAW-QC_PIPELINE_INPUT_3: "-rims_metadata.tsv"
    RAW-QC_PIPELINE_OUTPUT: "_launch_raw-qc_pipeline.txt"
    CHECK_RAW-QC_INPUT_1: "_launch_raw-qc_pipeline.txt"
    CHECK_RAW-QC_INPUT_2: "raw-qc_outputs_list.txt"
    CHECK_RAW-QC_INPUT_3: "_SAMPLEPLAN"
    CHECK_RAW-QC_OUTPUT: "_check_raw-qc_ok.txt"
    KDI_CREATE_DATASET_INPUT: "{{RUN}}_check_raw-qc_ok.txt"
    KDI_START_INPUT: "{{RUN}}_check_raw-qc_ok.txt"

general_path:
    PYTHON_BIN_DIR: "/bioinfo/local/build/Centos/python/python-2.7.12/bin/python2.7"
    BCL2FASTQ_BIN_DIR: "/bioinfo/local/build/Centos/bcl2fastq/bcl2fastq2-v2.18.0.12/bin/"
    CONDA_BIN_DIR: "/bioinfo/local/build/Centos/miniconda/miniconda3/bin/"
    SAMPLESHEET_DIR: "/data/transfert/Illumina/"
    RESEARCH_RULES_PATH: "{{RESEARCH_RULES_PATH}}/"
    RAW-QC_RULES_PATH: "{{RAWQC_PATH}}/raw-qc_snakemake/"
    OUTPUT_PATH: "{{OUTPUT_PATH}}"
    INPUT_DIR: "/data/transfert/Illumina/"
    PYTHON_PATH: "/bioinfo/pipelines/SOAPclient/python/kdi_{{ENV}}/instance"
    RULE_PATH_KDI: "/bioinfo/pipelines/kdi_api_scripts/{{ENV}}/KDI_snakemake/"
    DATA_TMP_OUTPATH: "{{OUTPUT_PATH}}"
    CREATE_KDI_CONF: "/bioinfo/pipelines/ngsdm/dev/Pipelines/SCRIPTS/createKDIconf_Snakemake.sh"
    SAMPLEDESCRIPTION_PATH: ".sampleDescription.txt"

samplesheet_checker:
    CLUSTER: "-q {{QUEUE}} -o {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_samplesheet_checker.out -e {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_samplesheet_checker.err -N snakemake_samplesheet_checker -l nodes=1:ppn=1,mem=1Gb"
    CLUSTER_ENV: "centos"
    PROJECT_TYPE: "{{PROJECT_TYPE}}"
    SCOPE: "{{SCOPE}}"
    PATH: "/bioinfo/pipelines/samplesheet-checker/{{ENV}}/"

bcl2fastq:
    CLUSTER: "-q {{QUEUE}} -o {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_bcl2fastq.out -e {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_bcl2fastq.err -N snakemake_bcl2fastq -l nodes=1:ppn=8,mem={{MEM_BCL2FASTQ}}"
    THREAD_NUMBER: "8"
    OPTIONAL_PARAMETERS: ""

check_fastq_length:
    CLUSTER: "-q {{QUEUE}} -o {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_check_fastq_length.out -e {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_check_fastq_length.err -N snakemake_check_fastq_length -l nodes=1:ppn=1,mem=2Gb"
    PATH: "{{RESEARCH_RULES_PATH}}/"

transfert_fastq_dir:
    CLUSTER: "-q {{QUEUE}} -o {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_transfert_fastq_dir.out -e {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_transfert_fastq_dir.err -N snakemake_transfert_fastq_dir -l nodes=1:ppn=1,mem=1Gb"
    PATH: "{{RESEARCH_RULES_PATH}}/"

manage_undetermined_fastq:
    CLUSTER: "-q {{QUEUE}} -o {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_manage_undetermined_fastq.out -e {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_manage_undetermined_fastq.err -N snakemake_manage_undetermined_fastq -l nodes=1:ppn=1,mem=1Gb"

samplesheet_to_sampleplan:
    CLUSTER: "-q {{QUEUE}} -o {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_samplesheet_to_sampleplan.out -e {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_samplesheet_to_sampleplan.err -N snakemake_samplesheet_to_sampleplan -l nodes=1:ppn=1,mem=1Gb"
    PATH: "{{RESEARCH_RULES_PATH}}/"

rims_metadata_launcher:
    CLUSTER: "-q {{QUEUE}} -o {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/rims_metadata_launcher.out -e {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/rims_metadata_launcher.err -N rims_metadata_launcher -l nodes=1:ppn=1,mem=1Gb"
    CLUSTER_ENV: "centos"
    PATH: "{{RESEARCH_RULES_PATH}}/"

samplesheet_to_sampledescription:
    CLUSTER: "-q {{QUEUE}} -o {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_samplesheet_to_sampledescription.out -e {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_samplesheet_to_sampledescription.err -N snakemake_samplesheet_to_sampledescription -l nodes=1:ppn=1,mem=1Gb"
    PATH: "{{RESEARCH_RULES_PATH}}/"

config_copy:
    CLUSTER: "-q {{QUEUE}} -o {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_config_copy.out -e {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_config_copy.err -N snakemake_config_copy -l nodes=1:ppn=1,mem=1Gb"
    PATH: "{{RESEARCH_RULES_PATH}}"

raw-qc_pipeline:
    CLUSTER: "-q {{QUEUE}} -o {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_raw-qc_pipeline.out -e {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_raw-qc_pipeline.err -N snakemake_raw-qc_pipeline -l nodes=1:ppn=1,mem=1Gb"
    PATH: "{{RAWQC_PATH}}/"

check_raw-qc:
    CLUSTER: "-q {{QUEUE}} -o {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_check_raw-qc.out -e {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_check_raw-qc.err -N snakemake_check_raw-qc -l nodes=1:ppn=1,mem=5Gb"
    PATH: "{{RAWQC_PATH}}/raw-qc_snakemake/"

gaingroup:
    CMD: "/bioinfo/local/bin/gaingroup -g w-ngsdm-g{{GAINGROUP}}"

kdi_create_dataset:
  CLUSTER: "-q {{QUEUE}} -o {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_KDI_create_dataset.out -e {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_KDI_create_dataset.err -N snakemake_raw-qc_KDI_create_dataset -l nodes=1:ppn=1,mem=1Gb"
kdi_start:
  CLUSTER: "-q {{QUEUE}} -o {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_KDI_start.out -e {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_KDI_start.err -N snakemake_raw-qc_KDI_start -l nodes=1:ppn=1,mem=1Gb"
kdi_export:
  CLUSTER: "-q {{QUEUE}} -o {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_KDI_export_rnaseq.out -e {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_KDI_export_rnaseq.err -N snakemake_raw-qc_KDI_export -l nodes=1:ppn=1,mem=1Gb"
kdi_conf_file_research:
  CLUSTER: "-q {{QUEUE}} -o {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_KDI_conf_file_research.out -e {{OUTPUT_PATH}}/RAW-QC-{{RUN}}/snakemake_KDI_conf_file_research.err -N snakemake_raw-qc_KDI_conf_file_research -l nodes=1:ppn=1,mem=1Gb"
