#
# Raw-QC config for MultiQC
#
#################################################################


custom_logo_url: https://science.curie.fr/plateformes/sequencage-adn-haut-debit-ngs/
custom_logo_title: Institut Curie
output_fn_name: 'rawqc_report.html'
module_order:
    - custom_content
    - fastqc:
        name: 'FastQC (raw)'
        info: 'This section of the report shows FastQC results before adapter trimming.'
        target: ''
        path_filters:
            - '*_fastqc.zip'
        path_filters_exclude:
            - '*_trimmed_fastqc.zip'
    - cutadapt:
        name: 'Trimming metrics (TrimGalore!)'
    - fastp:
        name: 'Trimming metrics (fastp)'
    - fastqc:
        name: 'FastQC (trimmed)'
        info: 'This section of the report shows FastQC results after adapter trimming.'
        path_filters:
            - '*_trimmed_fastqc.zip'



custom_data:
    example_files:
           file_format: 'tsv'
           section_name: 'Basic Metrics'
           description: 'Calculated basic metric for the raw-qc pipeline'
           plot_type: 'table'
           pconfig:
              id: 'stats'
              title: 'Basic Metrics'
              scale: 'RdYlBu'
              format: '{:,.0f}'             
              save_file: true

sp:
    example_files:
        fn: '*_Basic_Metrics.*'



table_cond_formatting_colours:
    - blue: '#337ab7'
    - lbue: '#5bc0de'
    - pass: '#5cb85c'
    - warn: '#f0ad4e'
    - fail: '#d9534f'


report_header_info:
    - Contact E-mail: 'ngs-lab@curie.fr'
    - Application Type: 'NGS'
    - Project Type: 'Application'
    - Sequencing Platform: 'HiSeq 2500 High Output V4'
    - Sequencing Setup: '2x125'

skip_generalstats:  true

