#
# Raw-QC config for MultiQC
#
#################################################################


custom_logo_url: https://science.curie.fr/plateformes/sequencage-adn-haut-debit-ngs/
custom_logo_title: Institut Curie
output_fn_name: 'rawqc_report.html'
module_order:
    - fastqc:
        name: 'FastQC (trimmed)'
        info: 'This section of the report shows FastQC results after adapter trimming.'
        target: ''
        path_filters:
            - '*_trimmed_fastqc.zip'
    - cutadapt
    - fastqc:
        name: 'FastQC (raw)'
        path_filters:
            - '*_fastqc.zip'

table_cond_formatting_colours:
    - blue: '#337ab7'
    - lbue: '#5bc0de'
    - pass: '#5cb85c'
    - warn: '#f0ad4e'
    - fail: '#d9534f'


report_header_info:
    - Contact E-mail: 'phil.ewels@scilifelab.se'
    - Application Type: 'RNA-seq'
    - Project Type: 'Application'
    - Sequencing Platform: 'HiSeq 2500 High Output V4'
    - Sequencing Setup: '2x125'

skip_generalstats: false
