#
# Raw-QC config for MultiQC
#
#################################################################

skip_generalstats: true
read_count_multiplier: 0.000001
read_count_prefix: 'M'
read_count_desc: 'millions'

###################################
## Custom content

custom_data:
    basic_metrics_SE:
         file_format: 'tsv'
         section_name: 'General Metrics'
         description: 'Calculated basic metric for the raw-qc pipeline'
         plot_type: 'table'
         pconfig:
            id: 'stats_SE'
            title: 'Basic Metrics'
            save_file: true
            col1_header: 'Sample ID'
         headers:
              Biological_name:
                title: 'Biological name'
              Total_reads:
                title: 'Total reads'
                format: '{:,.0f}'
              Sample_representation:
                title: 'Sample fraction (%)'
                min: 0
                max: 100
                format: '{:,.1f}'
                suffix: '%'
              Mean_length:
                title: 'Mean length'
                format: '{:,.0f}'
              Total_base:
                title: 'Total base'
                format: '{:,.0f}'
              Q20_R1:
                title: '>Q20 R1 (%)'
                min: 0
                max: 100
                format: '{:,.1f}'
                suffix: '%'
              Trimmed_Mean_length:
                title: 'Mean length after trimming'
                format: '{:,.0f}'
              Trimmed_reads:
                title: 'Trimmed reads (%)'
                min: 0
                max: 100
                format: '{:,.1f}'
                suffix: '%'
              Discarded_reads:
                title: 'Discarded reads (%)'
                min: 0
                max: 100
                format: '{:,.1f}'
                suffix: '%'

    basic_metrics_PE:
         file_format: 'tsv'
         section_name: 'General Metrics'
         description: 'Calculated basic metric for the raw-qc pipeline'
         plot_type: 'table'
         pconfig:
              id: 'stats_PE'
              title: 'Basic Metrics'
              save_file: true
              col1_header: 'Sample ID'
         headers:
              Biological_name:
                title: 'Biological name'
              Total_reads:
                title: 'Total reads'
                format: '{:,.0f}'
              Sample_representation:
                title: 'Sample fraction (%)'
                min: 0
                max: 100
                format: '{:,.1f}'
                suffix: '%'
              Mean_length:
                title: 'Mean length'
                format: '{:,.0f}'
              Total_base:
                title: 'Total base'
                format: '{:,.0f}'
              Q20_R1:
                title: '>Q20 R1 (%)'
                min: 0
                max: 100
                format: '{:,.1f}'
                suffix: '%'
              Q20_R2:
                title: '>Q20 R2 (%)'
                min: 0
                max: 100
                format: '{:,.1f}'
                suffix: '%'
              Trimmed_Mean_length:
                title: 'Mean length after trimming'
                min: 0
                max: 100
                format: '{:,.0f}'
              Trimmed_reads:
                title: 'Trimmed reads (%)'
                min: 0
                max: 100
                format: '{:,.1f}'
                suffix: '%'
              Discarded_reads:
                title: 'Discarded reads (%)'
                min: 0
                max: 100
                format: '{:,.1f}'
                suffix: '%'
    basic_metrics_SE_rawdata:
           file_format: 'tsv'
           section_name: 'Basic Metrics'
           description: 'Calculated basic metric for the raw-qc pipeline'
           plot_type: 'table'
           pconfig:
              id: 'stats_SE_rawdata'
              title: 'Basic Metrics for rawdata'
              save_file: true
              scale: 'RdYlGn'
           headers:
              Biological_name:
                title: 'Biological name'
              Total_reads:
                title: 'Total reads'
                format: '{:,.0f}'
              Sample_representation:
                title: 'Sample fraction (%)'
                min: 0
                max: 100
                format: '{:,.1f}'
                suffix: '%'
              Mean_length:
                title: 'Mean length'
                format: '{:,.0f}'
              Total_base:
                title: 'Total base'
                format: '{:,.0f}'
              Q20_R1:
                title: '>Q20 R1 (%)'
                min: 0
                max: 100
                format: '{:,.1f}'
                suffix: '%'
              Trimmed_Mean_length:
                title: 'Mean length after trimming'
                format: '{:,.0f}'
              Trimmed_reads:
                title: 'Trimmed reads (%)'
                min: 0
                max: 100
                format: '{:,.1f}'
                suffix: '%'
              Discarded_reads:
                title: 'Discarded reads (%)'
                min: 0
                max: 100
                format: '{:,.1f}'
                suffix: '%'
    basic_metrics_PE_rawdata:
           file_format: 'tsv'
           section_name: 'Basic Metrics for rawdata'
           description: 'Calculated basic metric for the raw-qc pipeline'
           plot_type: 'table'
           pconfig:
              id: 'stats_PE_rawdata'
              title: 'Basic Metrics'
              save_file: true
              scale: 'RdYlGn'
           headers:
              Biological_name:
                title: 'Biological name'
              Total_reads:
                title: 'Total reads'
                format: '{:,.0f}'
              Sample_representation:
                title: 'Sample fraction (%)'
                min: 0
                max: 100
                format: '{:,.1f}'
                suffix: '%'
              Mean_length:
                title: 'Mean length'
                format: '{:,.0f}'
              Total_base:
                title: 'Total base'
                format: '{:,.0f}'
              Q20_R1:
                title: '>Q20 R1 (%)'
                min: 0
                max: 100
                format: '{:,.1f}'
                suffix: '%'
              Q20_R2:
                title: '>Q20 R2 (%)'
                min: 0
                max: 100
                format: '{:,.1f}'
                suffix: '%'
              Trimmed_Mean_length:
                title: 'Mean length after trimming'
                format: '{:,.0f}'
              Trimmed_reads:
                title: 'Trimmed reads (%)'
                min: 0
                max: 100
                format: '{:,.1f}'
                suffix: '%'
              Discarded_reads:
                title: 'Discarded reads (%)'
                min: 0
                max: 100
                format: '{:,.1f}'
                suffix: '%'
    adapter_seq:
         file_format: 'tsv'
         section_name: 'Adapters'
         description: 'detected from the trimming report.'
         plot_type: 'table'
         pconfig:
            id: 'adapter'
            title: 'Adapter Seq'
            colour: 'blue'
            save_file: true
            scale: false
            col1_header: 'Sample ID'
         headers:
            sample_name:
              scale: false
              format: '{:.0f}'
              placement: 1000
            Adapter_sequence_read_1_regular_3':
              title: "Detected Adapter1"
              scale: false
              format: '{:.0f}'
              placement: 1000
            Adapter_sequence_read_2_regular_3':
              title: "Detected Adapter2"
              scale: false
              format: '{:.0f}'
              placement: 1000

sp:
    basic_metrics_SE:
        fn: 'mq_stats_SE.tsv'
    basic_metrics_PE:
        fn: 'mq_stats_PE.tsv'
    adapter_seq:
        fn: '*_Adaptor_seq.*'
    basic_metrics_SE_rawdata:
        fn: 'mq_stats_SE_rawdata.tsv'
    basic_metrics_PE_rawdata:
        fn: 'mq_stats_PE_rawdata.tsv'


table_columns_placement:
    stats_SE:
        Sample_name: 900
        Biological_name: 1000
        Total_reads: 1005
        Sample_representation: 1010
        Mean_length: 1015
        Total_base: 1020
        Q20_R1: 1025
        Trimmed_Mean_length: 1030
        Trimmed_reads: 1035
        Discarded_reads: 1040
    stats_PE:
        Sample_name: 900
        Biological_name: 1000
        Total_reads: 1005
        Sample_representation: 1010
        Mean_length: 1015
        Total_base: 1020
        Q20_R1: 1025
        Q20_R2: 1030
        Trimmed_Mean_length: 1035
        Trimmed_reads: 1040
        Discarded_reads: 1045
    stats_SE_rawdata:
        Sample_name: 900
        Biological_name: 1000
        Total_reads: 1005
        Sample_representation: 1010
        Mean_length: 1015
        Total_base: 1020
        Q20_R1: 1025
        Trimmed_Mean_length: 1030
        Trimmed_reads: 1035
        Discarded_reads: 1040
    stats_PE_rawdata:
        Sample_name: 900
        Biological_name: 1000
        Total_reads: 1005
        Sample_representation: 1010
        Mean_length: 1015
        Total_base: 1020
        Q20_R1: 1025
        Q20_R2: 1030
        Trimmed_Mean_length: 1035
        Trimmed_reads: 1040
        Discarded_reads: 1045


table_cond_formatting_rules:
    Q20_R1:
        pass:
            - gt: 94
        warn:
            - lt: 95
        fail:
            - lt: 90
    Q20_R2:
        pass:
            - gt: 94
        warn:
            - lt: 95
        fail:
            - lt: 90
    Discarded_reads:
        pass:
            - lt: 6
        warn:
            - gt: 5
        fail:
            - gt: 20 


###############################
## Modules

module_order:
    - custom_content
    - fastqc:
        name: 'FastQC (raw)'
        info: 'This section of the report shows FastQC results before adapter trimming.'
        target: ''
        path_filters:
            - '*_fastqc.zip'
        path_filters_exclude:
            - '*trimmed*fastqc.zip'
    - cutadapt:
        name: 'Trimming (TrimGalore!)'
    - fastp:
        name: 'Trimming (fastp)'
    - fastqc:
        name: 'FastQC (trimmed)'
        info: 'This section of the report shows FastQC results after adapter trimming.'
        path_filters:
              - '*trimmed*fastqc.zip'
    - fastq_screen:
        name: 'Fastq screen'

#############################
## Display

remove_sections:
  - fastqc_overrepresented_sequences
  - fastqc_status_checks
  - fastqc_sequence_counts
  - fastqc_sequence_duplication_levels

custom_content:
  order:
    - basic_metrics_SE
    - basic_metrics_PE
    - basic_metrics_SE_rawdata
    - basic_metrics_PE_rawdata
    - adapter_seq

report_section_order: 
  software-versions:
    order: -1000
  summary:
    order: -1100

