#
# Raw-QC config for MultiQC
#
#################################################################


title: Raw-QC Report
subtitle: A pipeline to control the quality and to trim adapters of FastQ files.
intro_text: >
    Raw-QC is a standard quality control pipeline written in bash.
    Input reads (paired or single) adapters are removed with Autotropos a wrapper of Atropos.
    Autotropos is able to detect adapters contents from a list of adapters.
custom_logo_url: https://science.curie.fr/plateformes/sequencage-adn-haut-debit-ngs/
custom_logo_title: Institut Curie
output_fn_name: 'rawqc_report.html'
skip_generalstats: true
{custom_content}
